### ISSUE TITLE
stuck with instructions in README

### ISSUE THREAD

**Issue by bbolker** [dushoff/makestuff#2]
I don't have any Makefile at all yet, so I started with step 2 in the README

- clone the repo
- next step says to `cp makestuff/simple.Makefile Makefile`, but no such file exists AFAICT ... (can't find it elsewhere in the repo either ...)

?? is it `makestuff/Makefile` ? That seems big and scary and doesn't suggest next steps to me ...

In the meantime I'll work on an old-style Makefile and try converting it over later ...

**Comment by bbolker** [comment]
On the other hand, I was able to guess this structure for a minimal Makefile:

```
soib_reprex_orig.Rout: soib_reprex_orig.R

include makestuff/wrapR.mk
```

which seems to be working. Next question would be, what do I need to add to enable `make makestuff` for downstream users?

**Comment by dushoff** [comment]
Thanks! I have completely redone the page and think that the instructions should just work (and will cover your concern about making makestuff).
